# Generated by Django 5.1.4 on 2026-04-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='certificaciones/')),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_agregado',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='distancia_km',
            field=models.PositiveIntegerField(default=0, help_text='Distancia desde el origen al centro de distribución en km'),
        ),
        migrations.AddField(
            model_name='producto',
            name='kilometro_cero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='certificaciones',
            field=models.ManyToManyField(blank=True, to='productos.certificacion'),
        ),
    ]
