# Generated by Django 5.1.4 on 2026-04-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_detallepedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
