# Generated by Django 5.1.4 on 2026-04-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_producto_imagen_pedido_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacion',
            name='icono_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
